### ISSUE TITLE
Help me pleas 

### ISSUE THREAD

**Issue by HEROTERRALTD** [ownport/sitemap-parser#2]
Can you pleas tell me in witch format the proxie should be ?

**Comment by ownport** [comment]
Are you using sitemap-parser as library or from command line?

**Comment by HEROTERRALTD** [comment]
coding

**Comment by ownport** [comment]
you need to pass the proxy parameter as 
```python
proxies = {'http': '127.0.0.1'}
sitemap = SitemapParser(proxies=proxies)
```
please change the local IP address to your proxy IP address.

**Comment by ownport** [comment]
as reference https://github.com/ownport/sitemap-parser/issues/3

**Comment by ownport** [comment]
Do you still have the issue with proxy parameter?

**Comment by HEROTERRALTD** [comment]
Nope all solved sir thank you

**Comment by ownport** [comment]
Ok, I'm closing the issue with reference to #3
